import Foundation

/// Protocol for encoding entities to SQLite values (generated by @Entity macro for better performance)
public protocol SQLiteEncodable {
    /// Encode this entity to a dictionary of column name to SQLite value
    func sqliteEncode() throws -> [String: SQLiteValue]
}

/// Protocol for decoding entities from SQLite statements (generated by @Entity macro for better performance)
public protocol SQLiteDecodable {
    /// Decode an entity from a SQLite statement row
    static func sqliteDecode(from statement: any SQLiteStatementProtocol) throws -> Self
}

/// Combined protocol for entities that can be both encoded and decoded
public typealias SQLiteCodable = SQLiteEncodable & SQLiteDecodable

/// Protocol that all entities must conform to
///
/// Required fields (enforced by @Entity macro):
/// - Either `id: UUIDV4` (standard entity) OR `#SyncKey` (syncable entity without id)
/// - `createdAt: Date` - Creation timestamp (auto-filled on insert)
/// - `updatedAt: Date` - Update timestamp (auto-filled on insert/update)
///
/// Note: Entities using @Entity macro will automatically get optimized SQLiteCodable implementations.
public protocol EntityProtocol: Codable, Sendable {
    var createdAt: Date { get }
    var updatedAt: Date { get }

    static var tableName: String { get }
    static var columns: [ColumnDefinition] { get }
    static var indexes: [IndexDefinition] { get }
    static var syncKeyColumns: [String] { get }
}

/// Default implementations
public extension EntityProtocol {
    static var indexes: [IndexDefinition] { [] }
    /// Default sync key columns (uses id for entities without #SyncKey)
    static var syncKeyColumns: [String] { ["id"] }
}
