import Foundation

/// Protocol for encoding entities to SQLite values (generated by @Entity macro for better performance)
public protocol SQLiteEncodable {
    /// Encode this entity to a dictionary of column name to SQLite value
    func sqliteEncode() throws -> [String: SQLiteValue]
}

/// Protocol for decoding entities from SQLite statements (generated by @Entity macro for better performance)
public protocol SQLiteDecodable {
    /// Decode an entity from a SQLite statement row
    static func sqliteDecode(from statement: any SQLiteStatementProtocol) throws -> Self
}

/// Combined protocol for entities that can be both encoded and decoded
public typealias SQLiteCodable = SQLiteEncodable & SQLiteDecodable

/// Protocol that all entities must conform to
///
/// Required fields (enforced by @Entity macro when readonly: false):
/// - Either `id: UUIDV7` (standard entity) OR `#SyncKey` (syncable entity without id)
/// - `createdAt: Date` - Creation timestamp (auto-filled on insert)
/// - `updatedAt: Date` - Update timestamp (auto-filled on insert/update)
///
/// When readonly: true, `createdAt` and `updatedAt` are optional, and `id` can be any type.
/// Readonly entities can only be used with ConnectionManager in readonly mode.
///
/// Note: Entities using @Entity macro will automatically get optimized SQLiteCodable implementations.
public protocol EntityProtocol: Codable, SQLiteCodable, Sendable {
    static var tableName: String { get }
    /// Explicit property-to-column mapping, generated from the same fields as the schema.
    static func columnName(for keyPath: AnyKeyPath) -> String?
    /// Values in syncKeyColumns order. A computed Identifiable.id need not be a stored column.
    static func sqliteIdentityValues(for id: Any) throws -> [SQLiteValue]
    static var columns: [ColumnDefinition] { get }
    static var indexes: [IndexDefinition] { get }
    static var fullTextIndexes: [FullTextIndexDefinition] { get }
    static var syncKeyColumns: [String] { get }
    static var isReadonly: Bool { get }
    /// Whether this entity participates in CloudKit synchronization. Fixed for a manager lifetime.
    static var isSyncEnabled: Bool { get }
}

/// Default implementations
public extension EntityProtocol {
    static func columnName(for keyPath: AnyKeyPath) -> String? { nil }

    static func sqliteIdentityValues(for id: Any) throws -> [SQLiteValue] {
        guard syncKeyColumns.count == 1, let value = id as? any SQLiteValueEncodable else {
            throw StoreError.invalidSchema("\(Self.self) must declare an identity codec for its key columns")
        }
        return [try value.sqliteEncode()]
    }

    static var indexes: [IndexDefinition] { [] }
    static var fullTextIndexes: [FullTextIndexDefinition] { [] }
    static var isReadonly: Bool { false }
    static var isSyncEnabled: Bool { !isReadonly }
}

/// Register the protocol accessor as well as the concrete stored-property key path.
/// Their debug descriptions and runtime representations can differ after optimization.
public func _swiftstoreIdentityKeyPath<E: Identifiable>(_ type: E.Type) -> AnyKeyPath {
    \E.id
}
